steps:
  - name: 'python:3.9'
    entrypoint: pip
    args: ['install', '-r', 'requirements.txt']
  - name: 'python:3.9'
    entrypoint: pytest
    args: ['--tb=short']
options:
  logging: CLOUD_LOGGING_ONLY
